<table class="pending-top-up">
    <thead>
        <tr>
            <th>Username</th>
            <th>Amount</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>john_doe</td>
            <td>$50</td>
            <td>
                <button>Approve</button>
                <button>Reject</button>
            </td>
        </tr>
        <tr>
            <td>jane_smith</td>
            <td>$100</td>
            <td>
                <button>Approve</button>
                <button>Reject</button>
            </td>
        </tr>
        <tr>
            <td>mark_jones</td>
            <td>$25</td>
            <td>
                <button>Approve</button>
                <button>Reject</button>
            </td>
        </tr>
    </tbody>
</table>
